// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANblL58g5pBc5vU_o9gHSnk8NVNJQaYiU',
    appId: '1:1013787800751:web:6d62e6a8bc9db0785d105a',
    messagingSenderId: '1013787800751',
    projectId: 'chikk-shopping-app',
    authDomain: 'chikk-shopping-app.firebaseapp.com',
    storageBucket: 'chikk-shopping-app.firebasestorage.app',
    measurementId: 'G-02SFX6MGW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9KpFKRjaKcFvBf6T4ojChDv2H2m9swjU',
    appId: '1:1013787800751:android:9973c5aa5f11f3205d105a',
    messagingSenderId: '1013787800751',
    projectId: 'chikk-shopping-app',
    storageBucket: 'chikk-shopping-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQyWD22LtHk85PXwmxYJ2Vv0SYu7DhyU',
    appId: '1:1013787800751:ios:d88ebf3832084e7a5d105a',
    messagingSenderId: '1013787800751',
    projectId: 'chikk-shopping-app',
    storageBucket: 'chikk-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.chikkShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQyWD22LtHk85PXwmxYJ2Vv0SYu7DhyU',
    appId: '1:1013787800751:ios:d88ebf3832084e7a5d105a',
    messagingSenderId: '1013787800751',
    projectId: 'chikk-shopping-app',
    storageBucket: 'chikk-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.chikkShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANblL58g5pBc5vU_o9gHSnk8NVNJQaYiU',
    appId: '1:1013787800751:web:30ee6b6001fc873d5d105a',
    messagingSenderId: '1013787800751',
    projectId: 'chikk-shopping-app',
    authDomain: 'chikk-shopping-app.firebaseapp.com',
    storageBucket: 'chikk-shopping-app.firebasestorage.app',
    measurementId: 'G-QC6T49CZFJ',
  );
}
